services:
  - type: web
    name: consumet-api # Name of the service
    runtime: docker
    repo: https://github.com/Dewuaa/inkora-reader.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 3000